Scroll up
igorlyakh/js-team-project pull request #19
Opened 2023-10-17 02:31 UTC by dmelnykova

CSS +-

2023-10-17 17:21 UTC, igorlyakh requested changes
1. В scroll-up.html не должен подключаться скрипт
2. В этом же файле убрать с кнопки слушателя
3. Пересмотреть логику js

2023-10-17 22:49 UTC, dmelnykova commented
Сейчас как? У меня работает кнопка без ошибок. Но проблема с иконкой, возможно в JS лишние строки, это мои попытки с этой иконкой. Она есть, но ее не видно. Про тот круг - я сделала.

2023-10-18 14:42 UTC, igorlyakh requested changes
Иконка есть, но она вне кружка, её нужно правильно поставить.

2023-10-18 23:09 UTC, igorlyakh approved these changes
Молодец

2023-10-18 23:09 UTC, merged